language: java

jdk: openjdk8

dist: xenial

services:
   - docker
   - xvfb

addons:
  sonarcloud:
    organization: "eyedema-palai103-school-agenda"
    token: ${SONAR_TOKEN}

# skip installation step
install: true

# cache:
#   directories:
#     - $HOME/.m2

script:
  - mvn clean verify -Pjacoco coveralls:report sonar:sonar org.pitest:pitest-maven:mutationCoverage
